import {NextResponse} from 'next/server';
export const maxDuration=60;
const count=(re,s='')=>(s.match(re)||[]).length;
const clean=h=>String(h||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
function score(html,text){const title=/<title[^>]*>/i.test(html),meta=/name=["']description["']/i.test(html),h1=count(/<h1\b/gi,html),h2=count(/<h2\b/gi,html),schema=count(/application\/ld\+json/gi,html),faq=/FAQPage|よくある質問|FAQ|Q&A/i.test(html+text),org=/Organization|Corporation|会社概要|企業情報|株式会社/i.test(html+text),trust=/代表者|所在地|住所|お問い合わせ|設立|資本金|実績/i.test(text),answer=/とは|について|方法|理由|料金|サービス|特徴|実績|事業/i.test(text);return{entity:Math.min(100,(org?60:25)+(title?20:0)+(meta?20:0)),structure:Math.min(100,(title?20:0)+(meta?20:0)+(h1===1?25:h1>0?15:0)+Math.min(35,h2*7)),schema:Math.min(100,schema*30+(org?25:0)+(faq?25:0)),faq:Math.min(100,(faq?55:10)+(answer?30:0)+(h2>=3?15:0)),trust:Math.min(100,(trust?60:20)+(org?20:0)+(text.length>1200?20:10)),citation:Math.min(100,(meta?20:0)+(answer?30:0)+(h2>=3?20:0)+(text.length>1500?30:text.length>700?15:5))}}
function roleOf(url,text){const s=(url+' '+text.slice(0,800)).toLowerCase();if(/company|about|会社概要|企業情報/.test(s))return['company','会社・運営情報',1.5];if(/service|business|product|サービス|事業/.test(s))return['service','サービス・事業',1.7];if(/faq|よくある質問|q&a/.test(s))return['faq','FAQ',1.4];if(/works|case|実績|導入事例/.test(s))return['proof','実績・事例',1.4];if(/contact|お問い合わせ/.test(s))return['contact','お問い合わせ',.7];return['other','一般ページ',1]}
function checks(html,text){const h1=count(/<h1\\b/gi,html),description=/name=["']description["']/i.test(html),schema=/application\\/ld\\+json/i.test(html),faq=/FAQPage|よくある質問|FAQ|Q&A/i.test(html+text),trust=/代表者|所在地|住所|設立|資本金|実績/i.test(text);return{h1,description,schema,faq,trust}}
function issuesOf(c){const a=[];if(c.h1===0)a.push('H1を1つ設定する');if(c.h1>1)a.push('H1を1ページ1つに整理する');if(!c.description)a.push('meta descriptionを追加する');if(!c.schema)a.push('ページ内容に合う構造化データを検討する');return a}
async function firecrawl(url){if(!process.env.FIRECRAWL_API_KEY)return null;try{const r=await fetch('https://api.firecrawl.dev/v1/scrape',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+process.env.FIRECRAWL_API_KEY},body:JSON.stringify({url,formats:['html']}),signal:AbortSignal.timeout(20000),cache:'no-store'});if(!r.ok)return null;const j=await r.json();return j?.data?.html||j?.html||null}catch{return null}}
async function one(url){try{const res=await fetch(url,{redirect:'follow',headers:{'user-agent':'Mozilla/5.0 Chrome/140 Safari/537.36','accept':'text/html,application/xhtml+xml','accept-language':'ja,en;q=0.8'},signal:AbortSignal.timeout(9000),cache:'no-store'});let html='';if(res.ok)html=await res.text();if(!html||html.length<200)html=await firecrawl(url)||'';if(!html)return{url,ok:false,reason:'ページ内容を取得できませんでした'};const text=clean(html).slice(0,30000);const title=html.match(/<title[^>]*>([\\s\\S]*?)<\\/title>/i)?.[1]?.replace(/<[^>]+>/g,' ').trim()||url;const ck=checks(html,text),role=roleOf(res.url||url,text);return{url:res.url||url,ok:true,title,textSample:text.slice(0,2600),categories:score(html,text),checks:ck,issues:issuesOf(ck),role:role[0],roleLabel:role[1],weight:role[2]}}catch{const html=await firecrawl(url);if(!html)return{url,ok:false,reason:'通常取得・代替取得ともに失敗しました'};const text=clean(html).slice(0,30000);const title=html.match(/<title[^>]*>([\\s\\S]*?)<\\/title>/i)?.[1]?.replace(/<[^>]+>/g,' ').trim()||url;const ck=checks(html,text),role=roleOf(url,text);return{url,ok:true,title,textSample:text.slice(0,2600),categories:score(html,text),checks:ck,issues:issuesOf(ck),role:role[0],roleLabel:role[1],weight:role[2],source:'firecrawl'}}}
export async function POST(req){try{const b=await req.json(),urls=Array.isArray(b?.urls)?b.urls.slice(0,20):[];if(!urls.length)return NextResponse.json({error:'診断するページがありません'},{status:400});const results=await Promise.all(urls.map(one));return NextResponse.json({ok:true,results,done:results.length,success:results.filter(x=>x.ok).length,failed:results.filter(x=>!x.ok).map(x=>x.url)});}catch(e){return NextResponse.json({error:e?.message||'バッチ診断に失敗しました'},{status:500})}}
