import {NextResponse} from 'next/server';
export const maxDuration=60;
const count=(re,s='')=>(s.match(re)||[]).length;
const clean=h=>String(h||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
function score(html,text){const title=/<title[^>]*>/i.test(html),meta=/name=["']description["']/i.test(html),h1=count(/<h1\b/gi,html),h2=count(/<h2\b/gi,html),schema=count(/application\/ld\+json/gi,html),faq=/FAQPage|よくある質問|FAQ|Q&A/i.test(html+text),org=/Organization|Corporation|会社概要|企業情報|株式会社/i.test(html+text),trust=/代表者|所在地|住所|お問い合わせ|設立|資本金|実績/i.test(text),answer=/とは|について|方法|理由|料金|サービス|特徴|実績|事業/i.test(text);return{entity:Math.min(100,(org?60:25)+(title?20:0)+(meta?20:0)),structure:Math.min(100,(title?20:0)+(meta?20:0)+(h1===1?25:h1>0?15:0)+Math.min(35,h2*7)),schema:Math.min(100,schema*30+(org?25:0)+(faq?25:0)),faq:Math.min(100,(faq?55:10)+(answer?30:0)+(h2>=3?15:0)),trust:Math.min(100,(trust?60:20)+(org?20:0)+(text.length>1200?20:10)),citation:Math.min(100,(meta?20:0)+(answer?30:0)+(h2>=3?20:0)+(text.length>1500?30:text.length>700?15:5))}}

async function firecrawlText(url){try{const raw=String(process.env.FIRECRAWL_API_KEY||'');const key=raw.replace(/[\u200B-\u200D\u2060\uFEFF\r\n\t]/g,'').trim().replace(/^["']|["']$/g,'').replace(/^Bearer\s+/i,'').trim();if(!key)return null;const res=await fetch('https://api.firecrawl.dev/v2/scrape',{method:'POST',headers:{'content-type':'application/json','accept':'application/json','authorization':'Bearer '+key},body:JSON.stringify({url,formats:['markdown'],location:{country:'JP',languages:['ja']}}),signal:AbortSignal.timeout(45000),cache:'no-store'});if(!res.ok)return null;const json=await res.json();const text=json?.data?.markdown||json?.markdown||'';return typeof text==='string'&&text.trim().length>=100?text:null}catch{return null}}
async function one(url){try{const res=await fetch(url,{redirect:'follow',headers:{'user-agent':'Mozilla/5.0 Chrome/140 Safari/537.36','accept':'text/html,application/xhtml+xml','accept-language':'ja,en;q=0.8'},signal:AbortSignal.timeout(9000),cache:'no-store'});if(!res.ok){const text=await firecrawlText(url);if(!text)return{url,ok:false};return{url,ok:true,title:url,textSample:text.slice(0,2600),categories:score('',text),source:'firecrawl'}}const html=await res.text(),text=clean(html).slice(0,30000);const title=html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.replace(/<[^>]+>/g,' ').trim()||url;return{url:res.url||url,ok:true,title,textSample:text.slice(0,2600),categories:score(html,text)}}catch{const text=await firecrawlText(url);if(!text)return{url,ok:false};const categories=score('',text);return{url,ok:true,title:url,textSample:text.slice(0,2600),categories,source:'firecrawl'}}}
export async function POST(req){try{const b=await req.json(),urls=Array.isArray(b?.urls)?b.urls.slice(0,20):[];if(!urls.length)return NextResponse.json({error:'診断するページがありません'},{status:400});const results=await Promise.all(urls.map(one));return NextResponse.json({ok:true,results,done:results.length,success:results.filter(x=>x.ok).length,failed:results.filter(x=>!x.ok).map(x=>x.url)});}catch(e){return NextResponse.json({error:e?.message||'バッチ診断に失敗しました'},{status:500})}}
