import { NextResponse } from 'next/server';
export const maxDuration = 60;
function normalizeInput(v){let s=String(v||'').trim();if(!/^https?:\/\//i.test(s))s='https://'+s;return s}
function blocked(h){return /^(localhost|127\.|0\.|10\.|192\.168\.|169\.254\.|::1)/i.test(h)}
function usable(u,start){if(u.origin!==start.origin||!/^https?:$/.test(u.protocol))return false;return !/\.(jpg|jpeg|png|gif|webp|svg|pdf|zip|mp4|mp3|css|js|xml)$/i.test(u.pathname)&&!/\/(login|signin|logout|cart|checkout|wp-admin)(\/|$)/i.test(u.pathname)}
async function sitemapUrls(start){const found=new Set(),visited=new Set();async function read(url,depth){if(depth>5||visited.has(url))return;visited.add(url);try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0','accept':'application/xml,text/xml,*/*'},signal:AbortSignal.timeout(4000),cache:'no-store'});if(!r.ok)return;const xml=await r.text();const re=/<loc[^>]*>([\s\S]*?)<\/loc>/gi;let m;while((m=re.exec(xml))!==null){try{const u=new URL(m[1].replace(/&amp;/g,'&').trim(),start);if(u.origin!==start.origin)continue;if(/\.xml$/i.test(u.pathname))await read(u.href,depth+1);else if(usable(u,start))found.add(u.href.split('#')[0])}catch{}}}catch{}}await Promise.all([read(new URL('/sitemap.xml',start).href,0),read(new URL('/sitemap_index.xml',start).href,0)]);return [...found]}
function links(html,base,start){const out=[];const re=/<a[^>]+href=["']([^"']+)["']/gi;let m;while((m=re.exec(String(html||'')))!==null){try{const u=new URL(m[1],base);u.hash='';['utm_source','utm_medium','utm_campaign','utm_term','utm_content','fbclid','gclid'].forEach(k=>u.searchParams.delete(k));if(usable(u,start))out.push(u.href)}catch{}}return out}
async function expand(start,seeds){const found=new Set(seeds);const priority=seeds.filter(x=>/company|about|service|business|product|works|case|faq/i.test(x));const sample=[...new Set([start.href,...priority.slice(0,20),...seeds.slice(0,15)])];await Promise.all(sample.map(async url=>{try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 Chrome/140 Safari/537.36','accept':'text/html'},signal:AbortSignal.timeout(5000),cache:'no-store'});if(!r.ok||!(r.headers.get('content-type')||'').includes('text/html'))return;const html=await r.text();links(html,r.url||url,start).forEach(x=>found.add(x))}catch{}}));return [...found]}
export async function POST(req){try{const body=await req.json();let start;try{start=new URL(normalizeInput(body?.url))}catch{return NextResponse.json({error:'URLの形式を確認してください'},{status:400})}if(!['http:','https:'].includes(start.protocol)||blocked(start.hostname))return NextResponse.json({error:'このURLは診断できません'},{status:400});const sitemap=await sitemapUrls(start);const expanded=await expand(start,sitemap);const all=[...new Set([start.href,...expanded])];return NextResponse.json({ok:true,url:start.href,total:all.length,urls:all,sitemapPages:sitemap.length,internallyDiscovered:Math.max(0,all.length-sitemap.length-1)})}catch(e){return NextResponse.json({error:e?.message||'ページ探索に失敗しました'},{status:500})}}
